# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './MainGUI_0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 826)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidgetCustomerList = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetCustomerList.setGeometry(QtCore.QRect(20, 70, 401, 671))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listWidgetCustomerList.setFont(font)
        self.listWidgetCustomerList.setObjectName("listWidgetCustomerList")
        self.pushButtonNewCustomer = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNewCustomer.setGeometry(QtCore.QRect(600, 70, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButtonNewCustomer.setFont(font)
        self.pushButtonNewCustomer.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButtonNewCustomer.setStyleSheet("background-color: rgb(0, 202, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 0);")
        self.pushButtonNewCustomer.setCheckable(True)
        self.pushButtonNewCustomer.setFlat(False)
        self.pushButtonNewCustomer.setObjectName("pushButtonNewCustomer")
        self.plainTextEditNewCustomer = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEditNewCustomer.setGeometry(QtCore.QRect(600, 160, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEditNewCustomer.setFont(font)
        self.plainTextEditNewCustomer.setObjectName("plainTextEditNewCustomer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonNewCustomer.setText(_translate("MainWindow", "New Customer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
